name: monorepo-split

on:
  push:
    tags: '*'

jobs:
  split-monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - fields
          - media
          - cms
    steps:
      - uses: actions/checkout@v3
      - id: previous-tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
      - name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'backstagephp'
          repository_name: '${{ matrix.package }}'
          branch: main
          tag: ${{ steps.previous-tag.outputs.tag }}
          user_name: 'Backstage'
          user_email: 'hello@backstagephp.com'